/*
DROP TABLE IF EXISTS card;

CREATE TABLE card (
  card_id INT AUTO_INCREMENT  PRIMARY KEY,
  word1 VARCHAR(250) NOT NULL,
  word2 VARCHAR(250) NOT NULL,
  word3 VARCHAR(250) NOT NULL,
  word4 VARCHAR(250) NOT NULL,
  word5 VARCHAR(250) NOT NULL
);
 */


INSERT INTO card (card_id, word1, word2, word3, word4, word5) VALUES
  (1,'Alcatraz', 'Smoke', 'Hazelnut', 'Diamond', 'Rose'),
  (2,'Puppet', 'Game', 'Vegas', 'Chest', 'Airplane'),
  (3,'Cord', 'Australia', 'Castle', 'Guard', 'Sheep'),
  (4,'Fleece', 'Mouse', 'Chain', 'Farm', 'Belgium'),
  (5,'Pepper', 'Triangle', 'Doll', 'Italy', 'Stage'),
  (6,'Heart', 'Moscow', 'Billiards', 'Unicorn', 'Orange'),
  (7,'Tokyo', 'Heel', 'Doll', 'Helicopter', 'Officer'),
  (8,'Melon', 'Anchor', 'Israel', 'Cactus', 'Tennis'),
  (9,'France', 'Moon', 'Canteen', 'Emperor penguin', 'Tool'),
  (10,'Brain', 'Mask', 'Concert', 'Troy', 'Shark'),
  (11,'Music', 'Neck', 'America', 'Coffee', 'Fever'),
  (12,'Barbie', 'Chocolate', 'Snow', 'Tie', 'Wind'),
  (13,'Thought', 'Frankenstein', 'Beam', 'Accent', 'Shower'),
  (14,'Ladybird', 'Mustard', 'Sherlock', 'Bottle', 'Virus'),
  (15,'Poison', 'Star', 'Wolf', 'Lena', 'Birthday'),
  (16,'Baker', 'Perfume', 'Flame', 'Zombie', 'Joker'),
  (17,'Buffy', 'Volcano', 'Passion', 'Cock', 'Electricity'),
  (18,'Genius', 'Dracula', 'Lion', 'Sock', 'Friday'),
  (19,'Pirate', 'Holidays', 'Fairy', 'Magnet', 'Fork'),
  (20,'Syrup', 'Forest', 'Scale', 'Zeus', 'Cockroach'),
  (21,'Dinosaur', 'Yellow', 'Mushroom', 'Pigeon', 'Pikachu'),
  (22,'Asterix', 'Robots', 'Comedy', 'Language', 'Hairdresser'),
  (23,'Cocktail', 'Mario', 'Cork', 'Violin', 'Peach'),
  (24,'Fox', 'Police', 'Simpson', 'Donut', 'Newspaper'),
  (25,'Mountains', 'Peanut', 'Light bulb', 'Jedi', 'Chili'),
  (26,'Sombrero', 'Cloverleaf', 'Button', 'Cheese', 'Chewbacca'),
  (27,'Revolver', 'Doctor', 'Strawberry', 'Nuclear power', 'Lottery'),
  (28,'Cemetery', 'Cupid', 'Umbrella', 'Jump', 'Root'),
  (29,'Treasure', 'Pilot', 'Mickey', 'Sewerage', 'Galaxy'),
  (30,'Moustache', 'Bubble', 'Chain', 'Strong', 'Cookie'),
  (31,'Croissant', 'Spirit', 'Straw', 'Nail', 'Potter'),
  (32,'Darwin', 'Tomato', 'Parachute', 'Cannon', 'Binoculars'),
  (33,'Fata morgana', 'Ramses', 'Fire', 'Intersection', 'Princess'),
  (34,'Spaceship', 'Bowling', 'Churchill', 'Aries', 'Spy'),
  (35,'Olympics', 'Climbing', 'Lawyer', 'Tolkien', 'River'),
  (36,'Carpet', 'Pony', 'Crown', 'New', 'Tarantino'),
  (37,'Heino', 'Ninja', 'Duvet', 'Hunter', 'Vegetables'),
  (38,'Cave', 'Hans', 'Casino', 'Candy', 'Fountain'),
  (39,'Light', 'Sofa', 'Mozart', 'Ring', 'Pizza'),
  (40, 'Picture', 'Fire department', 'Glass', 'Meatball', 'Greece'),
  (41, 'Tradition', 'Snake', 'Trophy', 'Picasso', 'Clock'),
  (42, 'Pyre', 'Wizard', 'Hockey', 'Banana', 'Helene'),
  (43, 'Caesar', 'Noodle', 'Hat', 'Dentist', 'Wheat'),
  (44, 'Mussel', 'Shakespeare', 'Giant', 'Foam', 'Cellar'),
  (45, 'Knives', 'Pillows', 'Armstrong', 'Sword', 'Flight'),
  (46, 'Ticket', 'Penguin', 'Cell', 'Gandhi', 'Oasis'),
  (47, 'Crocodile', 'Jewellery', 'Subway', 'Glasses', 'Falco'),
  (48, 'Jackson', 'Cigarette', 'Bracelet', 'Weather forecast', 'Tower'),
  (49, 'Tattoo', 'Spielberg', 'Apple', 'Mermaid', 'Boxes'),
  (50, 'Dwarf', 'Circus', 'Elvis', 'Lawn mower', 'Stone'),
  (51, 'Train', 'Sardine', 'Piece', 'Cleopatra', 'Window'),
  (52, 'Pomegranate', 'Filling', 'Brush', 'Pig', 'Avicii'),
  (53, 'Slipper', 'Sheet', 'Puma', 'Revolution', 'Sahara'),
  (54, 'Knight', 'Peace', 'Flower', 'Switzerland', 'Calendar'),
  (55, 'Schnitzel', 'Canada', 'Zoo', 'Whistle', 'Book');
